### ISSUE TITLE
Enabling for dark mode

### ISSUE THREAD

**Issue by glitch-ui** [virtualvivek/react-native-image-blur-shadow#1]
Hi @virtualvivek,

first of all thank you, I was looking a while for such a cool blurred drop shadow library for react-native!

Is it possible to also enable or add the blur for dark mode or just get the blur.png in a dark version to change it by my own in the assets folder?
Currently it doesn't look that good in dark mode because the blur png is white on a dark background.

**Comment by virtualvivek** [comment]
Hi @glitch-ui ,

Thanks a lot for showing support for this react-native addon :)

If you want to use it in dark mode or if your background color is anything except `#fff`
i believe this prop **shadowBackgroundColor** can help you !
If still it doesn't work please let me know.

**Comment by glitch-ui** [comment]
Hi @virtualvivek,

works perfectly!!! (reading the docs always helps... 😄)

Thank you 👍

**Comment by virtualvivek** [comment]
Hi @glitch-ui ,

Yup buddy Your welcome !!! :)
